### ISSUE TITLE
Namespaces.js not found on Linux (file is namespaces.js with lowercase "n")

### ISSUE THREAD

**Issue by vinsonyung** [HvyIndustries/crane#352]
Platform : Ubuntu 16.04 LTS
VSCode Version : 1.14.1
Crane Version : 0.3.7

```
Error: Cannot find module '../util/Namespaces'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/vinson/.vscode/extensions/HvyIndustries.crane-0.3.7/server/hvy/treeBuilderV2.js:9:22)
    at Object.<anonymous> (/home/vinson/.vscode/extensions/HvyIndustries.crane-0.3.7/server/hvy/treeBuilderV2.js:375:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 9:04:35 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by gustavoper** [comment]
Same error here: 

OS: Debian 3.16.43-2+deb8u1 (2017-06-18) x86_64 GNU/Linux

Version 1.13.1
Commit 379d2efb5539b09112c793d3d9a413017d736f89
Date 2017-06-14T18:18:03.540Z
Shell 1.6.6
Renderer 56.0.2924.87
Node 7.4.0




`

Error: Cannot find module '../util/Namespaces'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/[userDir]/.vscode/extensions/HvyIndustries.crane-0.3.7/server/hvy/treeBuilderV2.js:9:22)
    at Object.<anonymous> (/home/[userDir]/.vscode/extensions/HvyIndustries.crane-0.3.7/server/hvy/treeBuilderV2.js:375:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Error - 11:26:16] Connection to server got closed. Server will not be restarted.

`

**Comment by nevadascout** [comment]
Thanks, I'll work on a fix for this today. 

@vinsonyung @gustavoper Can you help me out please?

If you look in
```
/home/<user>/.vscode/extensions/HvyIndustries.crane-0.3.7/server/util/
```
There should be a file called `Namespaces.js`.

Does it have a lowercase or uppercase n? (`N` vs `n`)

**Comment by markalexandercastillo** [comment]
I'm experiencing the same problem and it's lowercased:
```
⇒  ls
Debug.js  Files.js  namespaces.js  Storage.js
```

**Comment by nevadascout** [comment]
@markalexandercastillo which OS are you using?

**Comment by markalexandercastillo** [comment]
I'm on Ubuntu 17.04.

**Comment by nevadascout** [comment]
Thanks, looks like this only affects Linux... I'll get a fix out later today

**Comment by jrfoell** [comment]
For those that want to keep truckin' in the meanwhile:
`mv ~/.vscode/extensions/HvyIndustries.crane-0.3.7/server/util/namespaces.js ~/.vscode/extensions/HvyIndustries.crane-0.3.7/server/util/Namespaces.js`

**Comment by nevadascout** [comment]
If you update to v0.3.8 this should be fixed.

Let me know if not! (I don't have a Linux machine to test on)

**Comment by vinsonio** [comment]
@nevadascout Thank you bro. It has been fixed.

**Comment by markalexandercastillo** [comment]
Works now. Thanks

**Comment by gustavoper** [comment]
Just for the record, worked like a charm! Thanks a lot
