### ISSUE TITLE
The PHP Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by martinandersen3d** [HvyIndustries/crane#362]
VS Code
Windows 10 64 Pro

Anyone know how to fix?

**Vs code > Output > Crane Language Server:**
```module.js:472
    throw err;
    ^

Error: Cannot find module './providers/workspaceSymbol'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Martin\.vscode\extensions\HvyIndustries.crane-0.3.8\server\server.js:17:27)
    at Object.<anonymous> (C:\Users\Martin\.vscode\extensions\HvyIndustries.crane-0.3.8\server\server.js:399:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
[Info  - 17:10:55] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^```

**Comment by nevadascout** [comment]
Which version of VS Code do you have?

**Comment by martinandersen3d** [comment]
Latest version (autoupdate)  

![vscodeversion](https://user-images.githubusercontent.com/19984581/30871123-1509cb62-a2e6-11e7-9c5e-34fad834a1b7.PNG)

**Comment by martinandersen3d** [comment]
okay found solution... 

1. in commandpromt cd  directory and execute **npm install** in this dir:
C:\Users\<username>\.vscode\extensions\HvyIndustries.crane-0.3.8

2. Just uninstall and reinstall "php intellisence crane" inside  vs-code.

This fix my issue:)

When did this happend? > Right after windows reinstall
