### ISSUE TITLE
Not working because of the version of Node.JS

### ISSUE THREAD

**Issue by xtlsoft** [HvyIndustries/crane#400]
Issues saying the extension is not working on modern VSCode versions are true, and I might have found the reason:
```
Here is the error stack:  Error: Cannot find module 'internal/util/types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:593:15)
    at Function.Module._load (internal/modules/cjs/loader.js:519:25)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at evalmachine.<anonymous>:44:31
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/graceful-fs/fs.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/graceful-fs/graceful-fs.js:3:27)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/unzip/node_modules/fstream/lib/reader.js:4:10)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/unzip/node_modules/fstream/fstream.js:2:18)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/unzip/lib/extract.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/node_modules/unzip/unzip.js:4:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/out/src/utils/Cranefs.js:12:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/out/src/crane.js:11:19)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/root/.local/share/code-server/extensions/hvyindustries.crane-0.3.8/out/src/extension.js:11:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:717:10)
    at Module.load (internal/modules/cjs/loader.js:611:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:550:12)
    at Function.Module._load (internal/modules/cjs/loader.js:542:3)
    at Function../lib/vscode/src/vs/workbench/services/extensions/node/extensionHostProcess.ts.Module._load (/src/packages/server/build/bootstrap-fork.js.gz:243165:29)
    at Function.load (/src/packages/server/build/bootstrap-fork.js.gz:165544:33)
    at Function.load [as _load] (/src/packages/server/build/bootstrap-fork.js.gz:244422:37)
    at Module.require (internal/modules/cjs/loader.js:649:17)
    at /src/packages/server/out/cli.js:259:25922
    at global.nativeNodeRequire.e (/src/packages/server/out/cli.js:259:25934)
    at loadCommonJSModule (/src/packages/server/build/bootstrap-fork.js.gz:170084:20)
    at ExtHostExtensionService._doActivateExtension (/src/packages/server/build/bootstrap-fork.js.gz:169778:13)
    at ExtHostExtensionService._activateExtension (/src/packages/server/build/bootstrap-fork.js.gz:169737:21)
    at ExtHostExtensionService.<anonymous> (/src/packages/server/build/bootstrap-fork.js.gz:169607:29) (at newlyActivatingExtension._host.actualActivateExtension.then (/src/packages/server/build/bootstrap-fork.js.gz:169443:25))
```

This is the error trace of Chrome Debug Console, running on code-server, my VSCode version: 
```
❯ code-server --version
1.1156-vsc1.33.1
```

As you see, it is because of the high NodeJS version.

I tried to downgrade the NodeJS on host machine, and then the problem disappeared.

This is absolutely fixable, and I'm considering opening a pull request.

**Comment by xtlsoft** [comment]
So has there been any contributors?

**Comment by nevadascout** [comment]
Please feel free to open a pull request for this! I'm no longer writing PHP so don't have a lot of time to maintain this.
